language: cpp

# Define the matrix for multi-platform builds
matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      env:
        - BUILD_TYPE=Release
        - CC=gcc
        - CXX=g++
    - os: windows
      compiler: msvc
      env:
        - BUILD_TYPE=Release
        - CC=cl
        - CXX=cl

# Cache dependencies to speed up builds
cache:
  directories:
    - $HOME/.cache

# Install dependencies
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update;
      sudo apt-get install -y cmake;
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install cmake;
    fi

# Script to configure, build, and test
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - cmake --build . --config $BUILD_TYPE
  - ctest --build-config $BUILD_TYPE

# Trigger builds on push and pull requests to main branch
branches:
  only:
    - main