image:
  - Visual Studio 2019
  - Ubuntu2004

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      BUILD_TYPE: Release
      CC: cl
      CXX: cl
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      BUILD_TYPE: Release
      CC: gcc
      CXX: g++

cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - /home/appveyor/.cache

install:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (
      choco install cmake --installargs "ADD_CMAKE_TO_PATH=System" &&
      cmake --version
    )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Ubuntu2004" (
      sudo apt-get update &&
      sudo apt-get install -y cmake
    )

build_script:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (
      cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_C_COMPILER=%CC% -DCMAKE_CXX_COMPILER=%CXX% -S . -B build &&
      cmake --build build --config %BUILD_TYPE%
    )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Ubuntu2004" (
      cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_C_COMPILER=%CC% -DCMAKE_CXX_COMPILER=%CXX% -S . -B build &&
      cmake --build build --config %BUILD_TYPE%
    )

test_script:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (
      cd build && ctest --build-config %BUILD_TYPE%
    )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Ubuntu2004" (
      cd build && ctest --build-config %BUILD_TYPE%
    )

branches:
  only:
    - main