version: '{build}'

image:
  - macos-sonoma

environment:
  global:
    # Skip unsupported Python versions
    CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* cp36-* cp37-* cp38-* cp39-* cp310-*
    # Set output directory for wheels
    CIBW_OUTPUT_DIR: wheelhouse
    # Specify Python versions to build for
    CIBW_BUILD: cp311-* cp312-* cp313-*
    # Platform-specific before_build commands
    CIBW_BEFORE_BUILD_MACOS: |
      cmake -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build
    CIBW_ARCHS_MACOS: auto universal2 arm64

build: off

install:
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "macos-sonoma") {
        # Set up Python for macOS
        python3 -m pip install --upgrade pip
        python3 -m pip install cibuildwheel==2.21.3
      }

for:
  - matrix:
      only:
        - image: macos-sonoma
    init:
      - sh: |
          # Install Rosetta for cross-compilation
          softwareupdate --install-rosetta --agree-to-license
          # Fix CMake installation
          brew install cmake || true
          brew link --overwrite cmake
          python3 --version
    build_script:
      - sh: python3 -m cibuildwheel --platform macos
    artifacts:
      - path: wheelhouse/*.whl
        name: macOS_Wheels