version: '{build}'

image:
  - Visual Studio 2019
  - Ubuntu2204
  - macOS

platform:
  - x64
  - ARM64

configuration:
  - Release

matrix:
  exclude:
    - image: Ubuntu2204
      platform: ARM64
    - image: macOS
      platform: ARM64

for:
  - matrix:
      only:
        - image: Visual Studio 2019
          platform: ARM64
    install:
      - ps: Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList 'modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community" --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --quiet' -Wait

  - matrix:
      only:
        - image: Visual Studio 2019
    before_build:
      - cmake -G "Visual Studio 16 2019" -A %PLATFORM% -B build
    build_script:
      - cmake --build build --config %CONFIGURATION%

  - matrix:
      only:
        - image: Ubuntu2204
    before_build:
      - sh: cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -B build
    build_script:
      - sh: cmake --build build

  - matrix:
      only:
        - image: macOS
    before_build:
      - sh: cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -B build
    build_script:
      - sh: cmake --build build